<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414134048 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE evenement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT NOT NULL, date_debut VARCHAR(255) NOT NULL, date_fin VARCHAR(255) NOT NULL, lieu VARCHAR(255) NOT NULL, etablissement_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B26681EFF631228 ON evenement (etablissement_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, filiere_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1D1C63B3180AA129 ON utilisateur (filiere_id)');
        $this->addSql('CREATE TABLE utilisateur_evenement (utilisateur_id INT NOT NULL, evenement_id INT NOT NULL, PRIMARY KEY (utilisateur_id, evenement_id))');
        $this->addSql('CREATE INDEX IDX_6B889D32FB88E14F ON utilisateur_evenement (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_6B889D32FD02F13 ON utilisateur_evenement (evenement_id)');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_B26681EFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id)');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3180AA129 FOREIGN KEY (filiere_id) REFERENCES filiere (id)');
        $this->addSql('ALTER TABLE utilisateur_evenement ADD CONSTRAINT FK_6B889D32FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_evenement ADD CONSTRAINT FK_6B889D32FD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE mentor');
        $this->addSql('DROP TABLE rendez_vous');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE etablissement ADD adresse VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE etablissement ADD telephone VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE etablissement ADD email VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE etablissement DROP description');
        $this->addSql('ALTER TABLE filiere ADD created_at VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE filiere ADD etablissement_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE filiere DROP debouches');
        $this->addSql('ALTER TABLE filiere ADD CONSTRAINT FK_2ED05D9EFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id)');
        $this->addSql('CREATE INDEX IDX_2ED05D9EFF631228 ON filiere (etablissement_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mentor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, specialite VARCHAR(255) NOT NULL, contact VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE rendez_vous (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, etudiant VARCHAR(255) NOT NULL, mentor VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_B26681EFF631228');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B3180AA129');
        $this->addSql('ALTER TABLE utilisateur_evenement DROP CONSTRAINT FK_6B889D32FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_evenement DROP CONSTRAINT FK_6B889D32FD02F13');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE utilisateur_evenement');
        $this->addSql('ALTER TABLE etablissement ADD description TEXT NOT NULL');
        $this->addSql('ALTER TABLE etablissement DROP adresse');
        $this->addSql('ALTER TABLE etablissement DROP telephone');
        $this->addSql('ALTER TABLE etablissement DROP email');
        $this->addSql('ALTER TABLE filiere DROP CONSTRAINT FK_2ED05D9EFF631228');
        $this->addSql('DROP INDEX IDX_2ED05D9EFF631228');
        $this->addSql('ALTER TABLE filiere ADD debouches TEXT NOT NULL');
        $this->addSql('ALTER TABLE filiere DROP created_at');
        $this->addSql('ALTER TABLE filiere DROP etablissement_id');
    }
}
